image: gitlab.icp.uni-stuttgart.de:4567/fweik/mdx

variables:
  CXX: clang++

test:
  script:
    - mkdir build && cd build
    - cmake -DENABLE_CLANG_TIDY=ON -DENABLE_SANITIZER_UNDEFINED_BEHAVIOR=ON ..
    - make
    - make test
